// <auto-generated />
namespace LabManager.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class I14 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(I14));
        
        string IMigrationMetadata.Id
        {
            get { return "201601021249111_I14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
